### ISSUE TITLE
"Node child_process module not supported in browsers" error after upgrade d3@4.10.0 to @4.10.2

### ISSUE THREAD

**Issue by LuquanLi** [d3/d3-request#27] opened 2017-09-13 18:22 UTC
Hi,

I recently have this error after d3 upgrade when running tests. Everything is good in previous version.

Error: (SystemJS) Node child_process module not supported in browsers.
  	Evaluating http://localhost:8889/static/scripts/vendor/github/jspm/nodelibs-child_process@0.1.0/index.js
  	Evaluating http://localhost:8889/static/scripts/vendor/github/jspm/nodelibs-child_process@0.1.0.js
  	Evaluating http://localhost:8889/static/scripts/vendor/npm/xmlhttprequest@1.8.0/lib/XMLHttpRequest.js
  	Evaluating http://localhost:8889/static/scripts/vendor/npm/xmlhttprequest@1.8.0.js
  	Evaluating http://localhost:8889/static/scripts/vendor/npm/d3-request@1.0.6/build/d3-request.node.js
  	Evaluating http://localhost:8889/static/scripts/vendor/npm/d3-request@1.0.6.js
  	Evaluating http://localhost:8889/static/scripts/vendor/npm/d3@4.10.2/build/d3.node.js
  	Evaluating http://localhost:8889/static/scripts/vendor/npm/d3@4.10.2.js

**Comment by mbostock** [comment] 2017-09-13 18:40
Duplicate of #24.

**Closed by mbostock** 2017-09-13 18:40 UTC
