### ISSUE TITLE
Latest Chrome version(?) doesn't accept null for user:password in xhr.send

### ISSUE THREAD

**Issue by teknocreator** [d3/d3-request#35] opened 2018-02-28 17:15 UTC
In this issue I'm using the latest D3 version 4 from the d3js.org site.

With the following code snippet (and with other similar d3-requests):

d3.json("stateslatlontopo.json")
.get(function(error, us) {
  if (error) throw error;
	svg.selectAll('.states')
		.data(topojson.feature(us, us.objects.stateslatlon).features)
		.enter()
		.append('path')
		.attr('class', 'states')
		.attr('d', path)
});

Chrome throws the following error:

d3.v4.js:11472 GET https://null:null@(web site base address)/stateslatlontopo.json 401 (Authorization Required)

I checked the d3 code and saw the defaults for user and password are set to null.  After reading the d3-request doc, saw that setting user and password to empty string ('') will pass along the user's id and password in the request.  And upon adding .user('').password('') after the d3.json, the page worked as it had previously without having to add those.  However, adding .user and .password is not needed in order to view the page in Firefox.  Just to note, there's no cross origin here as the JSON file is in the same directory as the web page.

Also note that this is occurring on a web server where users login with user id and password maintained by a Lightweight Directory Access Protocol (LDAP).  So that may come into play.  However, this issue is appearing on Chrome Version 64.0.3282.186 (Official Build) (32-bit) (which may have recently been updated) and not Firefox Quantum build 58.0.2 (32-bit).  I had just demonstrated the page I was working on last week without the need for the .user and .password.  Hence why I'm suspecting that a Chrome update may be causing this issue where null:null for userid and password no longer work when a user logins in to view a website.  I also removed the .user and .password from the request and retested this on a web severer where I didn't have to log in and used Chrome.  This also worked as expected with no error.  In that case, the following displayed in the Network and Headers tab in the Chrome debugger:

Request URL:https://null:null@(web page address)/stateslatlontopo.json
Request Method:GET
Status Code:200 OK

However, when I have to log into the other server and using Chrome:

Request URL:https://null:null@(web page address)/stateslatlontopo.json
Request Method:GET
Status Code:401 Authorization Required

In Firefox, the Request URL does not show the "null:null@" before the web page address when I view it on the Network tab either using the .user and .password or not.

So, I believe this may be due to a change in Chrome where null for user id and password is not valid where a user has to log in first in order to view the pages.  At least I discovered that adding the user and password options with empty strings still allowed the request and the page to function normally.  

I know d3-request will be deprecated in version 5 for d3-fetch and this only seems to affect the latest Chrome version where a user has to log in.  So perhaps this won't be an issue in the near future.  But thought I should bring it to your attention should others have a similar issue and that the work around would be to add the .user('').password('') to the request.

**Comment by jheeffer** [comment] 2018-03-01 15:33
We have had a similar problem and documented the bug here:

http://angieskazka.github.io/test-xhr-null-null/

Seems to have been introduced in this release (64.0.3282.168): https://chromereleases.googleblog.com/2018/02/stable-channel-update-for-desktop_13.html

And seems to have been fixed again in latest chrome stable release (64.0.3282.186):
https://chromereleases.googleblog.com/2018/02/stable-channel-update-for-desktop_22.html#gpluscomments

Can you confirm @teknocreator it is fixed for you too? However, it still occurs with serviceworkers, which still breaks our page, so it's not completely fixed. Trying out your user/pass empty string solution now.

This issue also seems related: https://github.com/d3/d3-request/issues/33

**Comment by mbostock** [comment] 2018-03-01 18:50
Yes, this looks like a duplicate of #33.

**Closed as completed by mbostock** 2018-03-01 18:50 UTC

**Comment by teknocreator** [comment] 2018-03-02 12:55
@jheeffer I updated my Chrome browser to the latest stable release (Version 64.0.3282.186 (Official Build) (64-bit), I work a different one when at home), cleared cookies/cache, removed my work around, and found that this version of Chrome still causes the issue.  After reading the first bugfix report listed by nkabrown in issue 33, it looks like release 65 of Chrome will contain the fix for this issue and is due to be released on March 6.  I'll check back then.  Interestingly, making user and password undefined apparently works as well according to the comments in [https://bugs.chromium.org/p/chromium/issues/detail?id=808018](url).  I'll continue to use what I know works at the moment and check to see if it's been fixed in a few days.

**Comment by teknocreator** [comment] 2018-03-09 12:15
@jheeffer @mbostock I just wanted to note that I confirmed Chrome release 65 has fixed this issue in the 32- and 64-bit versions.
